# This is the GitHub Action script
name: Build Android APK

on:
  push:
    branches:
      - master  # Or 'main' depending on the project
  workflow_dispatch: # Allows you to run this workflow manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17' # V2RayNG needs Java 17

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleDebug # This is the command Android Studio runs

    - name: Upload APK as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: v2rayNG-APK # Name of the downloadable file
        path: app/build/outputs/apk/debug/app-debug.apk # Path to the built APK
